version: '3'

tasks:

  build:
    desc: Build
    cmds:
      - task: mac
      - task: apk

  mac:
    desc: Build MacOS
    cmd: flutter build macos

  apk:
    desc: Build APK
    cmd: flutter build apk

  run:
    desc: Run on MacOS
    platforms: [darwin]
    cmd: open ./build/macos/Build/Products/Release/nihogo_geemu.app

  run-android:
    desc: Run on Android
    cmd: flutter devices --machine | jq -r '.[] | select(.targetPlatform | contains("android")) | .id' | head -n 1 | xargs flutter run -d

  test:
    desc: Test
    cmd: flutter test --no-pub --coverage

  coverage:
    desc: Generate HTML of coverage and open in browser
    preconditions:
      - test -f coverage/lcov.info
      - sh: "[ ! -z \"$(which genhtml)\" ]"
    cmds:
      - genhtml coverage/lcov.info -o coverage/html
      - open coverage/html/index.html

  lint:
    desc: Lint
    cmd: dart fix --dry-run

  lint-fix:
    desc: Lint Fix
    cmd: dart fix --apply
